# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_sessions.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SessionsScreen(object):
    def setupUi(self, SessionsScreen):
        SessionsScreen.setObjectName("SessionsScreen")
        SessionsScreen.resize(490, 650)
        SessionsScreen.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(SessionsScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 490, 650))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_top = QtWidgets.QFrame(self.frame)
        self.frame_top.setGeometry(QtCore.QRect(0, 0, 490, 50))
        self.frame_top.setStyleSheet("QFrame{\n"
"    background-color: rgb(72,72,73);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton#btn_toggle, #btn_exit {\n"
"    background-color: rgb(157, 121, 95);\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_toggle:hover, #btn_exit:hover {\n"
"    background-color: rgb(143, 110, 86);\n"
"}\n"
"QPushButton#btn_toggle:pressed, #btn_exit:pressed {\n"
"    background-color: rgb(130, 100, 78);\n"
"}\n"
"")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.btn_exit = QtWidgets.QPushButton(self.frame_top)
        self.btn_exit.setGeometry(QtCore.QRect(420, 10, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_top)
        self.btn_toggle.setGeometry(QtCore.QRect(10, 10, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_toggle.setFont(font)
        self.btn_toggle.setStyleSheet("")
        self.btn_toggle.setObjectName("btn_toggle")
        self.label = QtWidgets.QLabel(self.frame_top)
        self.label.setGeometry(QtCore.QRect(80, -24, 100, 100))
        self.label.setStyleSheet("border-image: url(:/images/images/logo.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_name = QtWidgets.QLabel(self.frame_top)
        self.label_name.setGeometry(QtCore.QRect(80, 13, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color: rgb(205,205,205);\n"
"background-color: rgba(0,0,0,0);")
        self.label_name.setObjectName("label_name")
        self.frame_left = QtWidgets.QFrame(self.frame)
        self.frame_left.setGeometry(QtCore.QRect(0, 50, 80, 600))
        self.frame_left.setStyleSheet("QFrame{\n"
"    background-color: rgb(72,72,73);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton#btn_list, #btn_request, #btn_delete {\n"
"    background-color: rgb(72,72,73);\n"
"    color: rgb(205, 205, 205);\n"
"    border: 0px;\n"
"}\n"
"QPushButton#btn_list:hover, #btn_request:hover, #btn_delete:hover {\n"
"    background-color: rgb(157, 121, 95);\n"
"}\n"
"QPushButton#btn_list:pressed, #btn_request:pressed, #btn_delete:pressed {\n"
"    background-color: rgba(130, 100, 78, 255);\n"
"}\n"
"")
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.btn_list = QtWidgets.QPushButton(self.frame_left)
        self.btn_list.setGeometry(QtCore.QRect(0, 0, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_list.setFont(font)
        self.btn_list.setStyleSheet("")
        self.btn_list.setObjectName("btn_list")
        self.btn_request = QtWidgets.QPushButton(self.frame_left)
        self.btn_request.setGeometry(QtCore.QRect(0, 40, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_request.setFont(font)
        self.btn_request.setStyleSheet("")
        self.btn_request.setObjectName("btn_request")
        self.btn_delete = QtWidgets.QPushButton(self.frame_left)
        self.btn_delete.setGeometry(QtCore.QRect(0, 80, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete.setFont(font)
        self.btn_delete.setStyleSheet("")
        self.btn_delete.setObjectName("btn_delete")
        self.frame_pages = QtWidgets.QFrame(self.frame)
        self.frame_pages.setGeometry(QtCore.QRect(80, 50, 410, 600))
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 410, 600))
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.stackedWidget.setStyleSheet("QPushButton#btn_request_id, #btn_delete_id {\n"
"    background-color: rgba(157, 121, 95, 255);\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_request_id:hover , #btn_delete_id:hover {\n"
"    background-color: rgba(143, 110, 86, 255);\n"
"}\n"
"QPushButton#btn_request_id:pressed , #btn_delete_id:pressed {\n"
"    background-color: rgba(130, 100, 78, 255);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgba(205,205,205,150);\n"
"    color: rgb(72,72,73);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"    padding-bottom: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QTextEdit {\n"
"    background-color: rgba(205,205,205,150);\n"
"    color: rgb(72,72,73);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: rgba(205,205,205,150);\n"
"    color: rgb(72,72,73);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"    padding-bottom: 2px;\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_list = QtWidgets.QWidget()
        self.page_list.setObjectName("page_list")
        self.label_sessions = QtWidgets.QLabel(self.page_list)
        self.label_sessions.setGeometry(QtCore.QRect(10, 2, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_sessions.setFont(font)
        self.label_sessions.setStyleSheet("color: rgba(0,0,0,150);\n"
"background-color: rgba(0,0,0,0);")
        self.label_sessions.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sessions.setObjectName("label_sessions")
        self.list_sessions = QtWidgets.QListWidget(self.page_list)
        self.list_sessions.setGeometry(QtCore.QRect(10, 40, 390, 550))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.list_sessions.setFont(font)
        self.list_sessions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_sessions.setStyleSheet("QListWidget#list_sessions {\n"
"    color: rgb(72,72,73);\n"
"    background-color: rgba(205,205,205,150);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"}\n"
"QListWidget::item:hover {\n"
"    color: rgb(205, 205, 205);\n"
"    background-color: rgba(157, 121, 95, 210);\n"
"}\n"
"QListWidget::item:selected {\n"
"    color: rgb(205, 205, 205);\n"
"    background-color: rgba(157, 121, 95, 255);\n"
"}")
        self.list_sessions.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_sessions.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_sessions.setWordWrap(False)
        self.list_sessions.setObjectName("list_sessions")
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_sessions.addItem(item)
        self.label_line = QtWidgets.QLabel(self.page_list)
        self.label_line.setGeometry(QtCore.QRect(12, -20, 130, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_line.setFont(font)
        self.label_line.setStyleSheet("color: rgba(255,255,255,255);")
        self.label_line.setObjectName("label_line")
        self.label_sessions_2 = QtWidgets.QLabel(self.page_list)
        self.label_sessions_2.setGeometry(QtCore.QRect(135, 7, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_sessions_2.setFont(font)
        self.label_sessions_2.setStyleSheet("color: rgba(0,0,0,150);\n"
"background-color: rgba(0,0,0,0);")
        self.label_sessions_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_sessions_2.setObjectName("label_sessions_2")
        self.list_sessions.raise_()
        self.label_line.raise_()
        self.label_sessions.raise_()
        self.label_sessions_2.raise_()
        self.stackedWidget.addWidget(self.page_list)
        self.page_request = QtWidgets.QWidget()
        self.page_request.setObjectName("page_request")
        self.label_line_4 = QtWidgets.QLabel(self.page_request)
        self.label_line_4.setGeometry(QtCore.QRect(12, -20, 130, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_line_4.setFont(font)
        self.label_line_4.setStyleSheet("color: rgba(255,255,255,255);")
        self.label_line_4.setObjectName("label_line_4")
        self.label_request_2 = QtWidgets.QLabel(self.page_request)
        self.label_request_2.setGeometry(QtCore.QRect(135, 7, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_request_2.setFont(font)
        self.label_request_2.setStyleSheet("color: rgba(0,0,0,150);\n"
"background-color: rgba(0,0,0,0);")
        self.label_request_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_request_2.setObjectName("label_request_2")
        self.label_request = QtWidgets.QLabel(self.page_request)
        self.label_request.setGeometry(QtCore.QRect(10, 2, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_request.setFont(font)
        self.label_request.setStyleSheet("color: rgba(0,0,0,150);\n"
"background-color: rgba(0,0,0,0);")
        self.label_request.setAlignment(QtCore.Qt.AlignCenter)
        self.label_request.setObjectName("label_request")
        self.input_session = QtWidgets.QLineEdit(self.page_request)
        self.input_session.setGeometry(QtCore.QRect(10, 40, 390, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_session.setFont(font)
        self.input_session.setStyleSheet("")
        self.input_session.setObjectName("input_session")
        self.session_info = QtWidgets.QTextEdit(self.page_request)
        self.session_info.setGeometry(QtCore.QRect(10, 130, 390, 461))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.session_info.setFont(font)
        self.session_info.setStyleSheet("")
        self.session_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.session_info.setReadOnly(True)
        self.session_info.setObjectName("session_info")
        self.btn_request_id = QtWidgets.QPushButton(self.page_request)
        self.btn_request_id.setGeometry(QtCore.QRect(10, 80, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_request_id.setFont(font)
        self.btn_request_id.setStyleSheet("")
        self.btn_request_id.setObjectName("btn_request_id")
        self.stackedWidget.addWidget(self.page_request)
        self.page_delete = QtWidgets.QWidget()
        self.page_delete.setObjectName("page_delete")
        self.label_line_3 = QtWidgets.QLabel(self.page_delete)
        self.label_line_3.setGeometry(QtCore.QRect(12, -20, 130, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_line_3.setFont(font)
        self.label_line_3.setStyleSheet("color: rgba(255,255,255,255);")
        self.label_line_3.setObjectName("label_line_3")
        self.label_delete = QtWidgets.QLabel(self.page_delete)
        self.label_delete.setGeometry(QtCore.QRect(135, 7, 265, 20))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_delete.setFont(font)
        self.label_delete.setStyleSheet("color: rgba(0,0,0,150);\n"
"background-color: rgba(0,0,0,0);")
        self.label_delete.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_delete.setObjectName("label_delete")
        self.label_delete_2 = QtWidgets.QLabel(self.page_delete)
        self.label_delete_2.setGeometry(QtCore.QRect(10, 2, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_delete_2.setFont(font)
        self.label_delete_2.setStyleSheet("color: rgba(0,0,0,150);\n"
"background-color: rgba(0,0,0,0);")
        self.label_delete_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delete_2.setObjectName("label_delete_2")
        self.label_delete_3 = QtWidgets.QPlainTextEdit(self.page_delete)
        self.label_delete_3.setGeometry(QtCore.QRect(10, 80, 390, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_delete_3.setFont(font)
        self.label_delete_3.setStyleSheet("")
        self.label_delete_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_delete_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_delete_3.setReadOnly(True)
        self.label_delete_3.setObjectName("label_delete_3")
        self.input_delete = QtWidgets.QLineEdit(self.page_delete)
        self.input_delete.setGeometry(QtCore.QRect(10, 40, 390, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_delete.setFont(font)
        self.input_delete.setStyleSheet("")
        self.input_delete.setObjectName("input_delete")
        self.btn_delete_id = QtWidgets.QPushButton(self.page_delete)
        self.btn_delete_id.setGeometry(QtCore.QRect(10, 140, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete_id.setFont(font)
        self.btn_delete_id.setStyleSheet("")
        self.btn_delete_id.setObjectName("btn_delete_id")
        self.stackedWidget.addWidget(self.page_delete)
        self.page_empty = QtWidgets.QWidget()
        self.page_empty.setObjectName("page_empty")
        self.stackedWidget.addWidget(self.page_empty)
        self.frame_bg = QtWidgets.QFrame(self.frame)
        self.frame_bg.setGeometry(QtCore.QRect(0, 0, 490, 650))
        self.frame_bg.setStyleSheet("")
        self.frame_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg.setObjectName("frame_bg")
        self.label_bg = QtWidgets.QLabel(self.frame_bg)
        self.label_bg.setGeometry(QtCore.QRect(0, 0, 490, 650))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bg.setFont(font)
        self.label_bg.setStyleSheet("border-image: url(:/images/images/bg.jpg);")
        self.label_bg.setText("")
        self.label_bg.setObjectName("label_bg")
        self.frame_bg.raise_()
        self.frame_pages.raise_()
        self.frame_top.raise_()
        self.frame_left.raise_()
        SessionsScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SessionsScreen)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(SessionsScreen)

    def retranslateUi(self, SessionsScreen):
        _translate = QtCore.QCoreApplication.translate
        SessionsScreen.setWindowTitle(_translate("SessionsScreen", "MainWindow"))
        self.btn_exit.setText(_translate("SessionsScreen", "EXIT"))
        self.btn_toggle.setText(_translate("SessionsScreen", " >"))
        self.label_name.setText(_translate("SessionsScreen", "GUITAR AIO - Sessions"))
        self.btn_list.setText(_translate("SessionsScreen", "LIST"))
        self.btn_request.setText(_translate("SessionsScreen", "REQUEST"))
        self.btn_delete.setText(_translate("SessionsScreen", "DELETE"))
        self.label_sessions.setText(_translate("SessionsScreen", "YOUR SESSIONS"))
        __sortingEnabled = self.list_sessions.isSortingEnabled()
        self.list_sessions.setSortingEnabled(False)
        item = self.list_sessions.item(0)
        item.setText(_translate("SessionsScreen", "1 - 24:43"))
        item = self.list_sessions.item(1)
        item.setText(_translate("SessionsScreen", "2"))
        item = self.list_sessions.item(2)
        item.setText(_translate("SessionsScreen", "3"))
        item = self.list_sessions.item(3)
        item.setText(_translate("SessionsScreen", "4"))
        item = self.list_sessions.item(4)
        item.setText(_translate("SessionsScreen", "5"))
        item = self.list_sessions.item(5)
        item.setText(_translate("SessionsScreen", "6"))
        item = self.list_sessions.item(6)
        item.setText(_translate("SessionsScreen", "7"))
        item = self.list_sessions.item(7)
        item.setText(_translate("SessionsScreen", "8"))
        item = self.list_sessions.item(8)
        item.setText(_translate("SessionsScreen", "9"))
        item = self.list_sessions.item(9)
        item.setText(_translate("SessionsScreen", "10"))
        item = self.list_sessions.item(10)
        item.setText(_translate("SessionsScreen", "11"))
        item = self.list_sessions.item(11)
        item.setText(_translate("SessionsScreen", "12"))
        item = self.list_sessions.item(12)
        item.setText(_translate("SessionsScreen", "13"))
        item = self.list_sessions.item(13)
        item.setText(_translate("SessionsScreen", "14"))
        item = self.list_sessions.item(14)
        item.setText(_translate("SessionsScreen", "15"))
        item = self.list_sessions.item(15)
        item.setText(_translate("SessionsScreen", "16"))
        item = self.list_sessions.item(16)
        item.setText(_translate("SessionsScreen", "17"))
        item = self.list_sessions.item(17)
        item.setText(_translate("SessionsScreen", "18"))
        item = self.list_sessions.item(18)
        item.setText(_translate("SessionsScreen", "19"))
        item = self.list_sessions.item(19)
        item.setText(_translate("SessionsScreen", "20"))
        item = self.list_sessions.item(20)
        item.setText(_translate("SessionsScreen", "21"))
        item = self.list_sessions.item(21)
        item.setText(_translate("SessionsScreen", "22"))
        item = self.list_sessions.item(22)
        item.setText(_translate("SessionsScreen", "23"))
        item = self.list_sessions.item(23)
        item.setText(_translate("SessionsScreen", "24"))
        self.list_sessions.setSortingEnabled(__sortingEnabled)
        self.label_line.setText(_translate("SessionsScreen", "________________"))
        self.label_sessions_2.setText(_translate("SessionsScreen", "- See your session list"))
        self.label_line_4.setText(_translate("SessionsScreen", "________________"))
        self.label_request_2.setText(_translate("SessionsScreen", "- Request more info about your session"))
        self.label_request.setText(_translate("SessionsScreen", "REQUEST"))
        self.input_session.setPlaceholderText(_translate("SessionsScreen", "Enter session ID"))
        self.session_info.setPlaceholderText(_translate("SessionsScreen", "Session info"))
        self.btn_request_id.setText(_translate("SessionsScreen", "REQUEST"))
        self.label_line_3.setText(_translate("SessionsScreen", "________________"))
        self.label_delete.setText(_translate("SessionsScreen", "- Delete session from your session list"))
        self.label_delete_2.setText(_translate("SessionsScreen", "DELETE"))
        self.label_delete_3.setPlainText(_translate("SessionsScreen", "Use button below to delete session from  your sessin list.\n"
"You can not reverse this."))
        self.input_delete.setPlaceholderText(_translate("SessionsScreen", "Session ID"))
        self.btn_delete_id.setText(_translate("SessionsScreen", "DELETE"))
import res_rc
