# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutScreen(object):
    def setupUi(self, AboutScreen):
        AboutScreen.setObjectName("AboutScreen")
        AboutScreen.resize(490, 650)
        AboutScreen.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(AboutScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(0, 50, 490, 650))
        self.frame_main.setStyleSheet("QFrame#frame_main {\n"
"    border-image: url(:/images/images/bg.jpg);\n"
"}\n"
"QPushButton#btn_fb, #btn_ig, #btn_yt, #btn_in, #btn_git {\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: rgb(157, 121, 95);\n"
"}\n"
"QPushButton#btn_fb:hover, #btn_ig:hover, #btn_yt:hover, #btn_in:hover, #btn_git:hover {\n"
"    color: rgb(143, 110, 86);\n"
"    font-size: 64px\n"
"}\n"
"QPushButton#btn_fb:pressed, #btn_ig:pressed, #btn_yt:pressed, #btn_in:pressed, #btn_git:pressed {\n"
"    color: rgb(130, 100, 78);\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: rgba(205,205,205,150);\n"
"    color: rgb(72,72,73);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"    padding-bottom: 2px;\n"
"}")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.text_app = QtWidgets.QPlainTextEdit(self.frame_main)
        self.text_app.setGeometry(QtCore.QRect(30, 30, 430, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_app.setFont(font)
        self.text_app.setStyleSheet("")
        self.text_app.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_app.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_app.setReadOnly(True)
        self.text_app.setObjectName("text_app")
        self.btn_follow = QtWidgets.QPushButton(self.frame_main)
        self.btn_follow.setGeometry(QtCore.QRect(30, 90, 430, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_follow.setFont(font)
        self.btn_follow.setStyleSheet("QPushButton#btn_follow {\n"
"    background-color: rgb(157, 121, 95);\n"
"    color: rgb(205,205,205);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_follow:hover {\n"
"    background-color: rgb(143, 110, 86);\n"
"}\n"
"QPushButton#btn_follow:pressed {\n"
"    background-color: rgb(130, 100, 78);\n"
"}")
        self.btn_follow.setObjectName("btn_follow")
        self.btn_fb = QtWidgets.QPushButton(self.frame_main)
        self.btn_fb.setGeometry(QtCore.QRect(22, 150, 70, 70))
        self.btn_fb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(40)
        self.btn_fb.setFont(font)
        self.btn_fb.setStyleSheet("")
        self.btn_fb.setObjectName("btn_fb")
        self.btn_ig = QtWidgets.QPushButton(self.frame_main)
        self.btn_ig.setGeometry(QtCore.QRect(22, 230, 70, 70))
        self.btn_ig.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(40)
        self.btn_ig.setFont(font)
        self.btn_ig.setObjectName("btn_ig")
        self.btn_yt = QtWidgets.QPushButton(self.frame_main)
        self.btn_yt.setGeometry(QtCore.QRect(22, 310, 70, 70))
        self.btn_yt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(40)
        self.btn_yt.setFont(font)
        self.btn_yt.setObjectName("btn_yt")
        self.btn_in = QtWidgets.QPushButton(self.frame_main)
        self.btn_in.setGeometry(QtCore.QRect(22, 390, 70, 70))
        self.btn_in.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(40)
        self.btn_in.setFont(font)
        self.btn_in.setObjectName("btn_in")
        self.btn_git = QtWidgets.QPushButton(self.frame_main)
        self.btn_git.setGeometry(QtCore.QRect(22, 470, 70, 70))
        self.btn_git.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.btn_git.setFont(font)
        self.btn_git.setObjectName("btn_git")
        self.text_fb = QtWidgets.QPlainTextEdit(self.frame_main)
        self.text_fb.setGeometry(QtCore.QRect(50, 158, 411, 54))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_fb.setFont(font)
        self.text_fb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.text_fb.setStyleSheet("border-left: none;")
        self.text_fb.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_fb.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_fb.setReadOnly(True)
        self.text_fb.setObjectName("text_fb")
        self.text_ig = QtWidgets.QPlainTextEdit(self.frame_main)
        self.text_ig.setGeometry(QtCore.QRect(50, 238, 411, 54))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_ig.setFont(font)
        self.text_ig.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.text_ig.setStyleSheet("border-left: none;")
        self.text_ig.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_ig.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_ig.setReadOnly(True)
        self.text_ig.setObjectName("text_ig")
        self.text_yt = QtWidgets.QPlainTextEdit(self.frame_main)
        self.text_yt.setGeometry(QtCore.QRect(50, 318, 411, 54))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_yt.setFont(font)
        self.text_yt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.text_yt.setStyleSheet("border-left: none;")
        self.text_yt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_yt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_yt.setReadOnly(True)
        self.text_yt.setObjectName("text_yt")
        self.text_in = QtWidgets.QPlainTextEdit(self.frame_main)
        self.text_in.setGeometry(QtCore.QRect(50, 398, 411, 54))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_in.setFont(font)
        self.text_in.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.text_in.setStyleSheet("border-left: none;")
        self.text_in.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_in.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_in.setReadOnly(True)
        self.text_in.setObjectName("text_in")
        self.text_git = QtWidgets.QPlainTextEdit(self.frame_main)
        self.text_git.setGeometry(QtCore.QRect(50, 478, 411, 54))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_git.setFont(font)
        self.text_git.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.text_git.setStyleSheet("border-left: none;")
        self.text_git.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_git.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_git.setReadOnly(True)
        self.text_git.setObjectName("text_git")
        self.text_fb.raise_()
        self.text_app.raise_()
        self.btn_follow.raise_()
        self.btn_fb.raise_()
        self.text_ig.raise_()
        self.btn_ig.raise_()
        self.text_yt.raise_()
        self.text_in.raise_()
        self.text_git.raise_()
        self.btn_yt.raise_()
        self.btn_in.raise_()
        self.btn_git.raise_()
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setGeometry(QtCore.QRect(0, 0, 490, 50))
        self.frame_top.setStyleSheet("QFrame {\n"
"    background-color: rgb(72,72,73);\n"
"}\n"
"QPushButton#btn_exit {\n"
"    background-color: rgb(157, 121, 95);\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_exit:hover {\n"
"    background-color: rgb(143, 110, 86);\n"
"}\n"
"QPushButton#btn_exit:pressed {\n"
"    background-color: rgb(130, 100, 78);\n"
"}")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.app_name = QtWidgets.QLabel(self.frame_top)
        self.app_name.setGeometry(QtCore.QRect(30, 13, 208, 50))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setStyleSheet("color: rgb(205,205,205);\n"
"background-color: rgba(0,0,0,0);")
        self.app_name.setObjectName("app_name")
        self.logo = QtWidgets.QLabel(self.frame_top)
        self.logo.setGeometry(QtCore.QRect(30, -24, 100, 100))
        self.logo.setStyleSheet("border-image: url(:/images/images/logo.jpg);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.btn_exit = QtWidgets.QPushButton(self.frame_top)
        self.btn_exit.setGeometry(QtCore.QRect(400, 10, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("")
        self.btn_exit.setObjectName("btn_exit")
        self.logo.raise_()
        self.app_name.raise_()
        self.btn_exit.raise_()
        self.frame_top.raise_()
        self.frame_main.raise_()
        AboutScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(AboutScreen)
        QtCore.QMetaObject.connectSlotsByName(AboutScreen)

    def retranslateUi(self, AboutScreen):
        _translate = QtCore.QCoreApplication.translate
        AboutScreen.setWindowTitle(_translate("AboutScreen", "MainWindow"))
        self.text_app.setPlainText(_translate("AboutScreen", "Guitar AIO is an open source software designed to help guitar players find songs they want to learn."))
        self.btn_follow.setText(_translate("AboutScreen", "FOLLOW US"))
        self.btn_fb.setText(_translate("AboutScreen", "E"))
        self.btn_ig.setText(_translate("AboutScreen", "Q"))
        self.btn_yt.setText(_translate("AboutScreen", "M"))
        self.btn_in.setText(_translate("AboutScreen", "C"))
        self.btn_git.setText(_translate("AboutScreen", ")"))
        self.text_fb.setPlainText(_translate("AboutScreen", "             You can find us on Facebook. "))
        self.text_ig.setPlainText(_translate("AboutScreen", "             You can find us on Instagram. "))
        self.text_yt.setPlainText(_translate("AboutScreen", "             You can find us on YouTube. "))
        self.text_in.setPlainText(_translate("AboutScreen", "             You can find us on LinkedIn. "))
        self.text_git.setPlainText(_translate("AboutScreen", "             You can find us on GitHub. "))
        self.app_name.setText(_translate("AboutScreen", "GUITAR AIO - About us"))
        self.btn_exit.setText(_translate("AboutScreen", "EXIT"))
import res_rc
