# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminScreen(object):
    def setupUi(self, AdminScreen):
        AdminScreen.setObjectName("AdminScreen")
        AdminScreen.resize(490, 650)
        AdminScreen.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(AdminScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 490, 650))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_top = QtWidgets.QFrame(self.frame)
        self.frame_top.setGeometry(QtCore.QRect(0, 0, 490, 50))
        self.frame_top.setStyleSheet("QFrame{\n"
"    background-color: rgb(72,72,73);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton#btn_toggle, #btn_exit {\n"
"    background-color: rgb(157, 121, 95);\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_toggle:hover, #btn_exit:hover {\n"
"    background-color: rgb(143, 110, 86);\n"
"}\n"
"QPushButton#btn_toggle:pressed, #btn_exit:pressed {\n"
"    background-color: rgb(130, 100, 78);\n"
"}\n"
"")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.btn_exit = QtWidgets.QPushButton(self.frame_top)
        self.btn_exit.setGeometry(QtCore.QRect(420, 10, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_top)
        self.btn_toggle.setGeometry(QtCore.QRect(10, 10, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_toggle.setFont(font)
        self.btn_toggle.setStyleSheet("")
        self.btn_toggle.setObjectName("btn_toggle")
        self.label = QtWidgets.QLabel(self.frame_top)
        self.label.setGeometry(QtCore.QRect(80, -24, 100, 100))
        self.label.setStyleSheet("border-image: url(:/images/images/logo.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_name = QtWidgets.QLabel(self.frame_top)
        self.label_name.setGeometry(QtCore.QRect(80, 13, 331, 50))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color: rgb(205,205,205);\n"
"background-color: rgba(0,0,0,0);")
        self.label_name.setObjectName("label_name")
        self.frame_left = QtWidgets.QFrame(self.frame)
        self.frame_left.setGeometry(QtCore.QRect(0, 50, 80, 600))
        self.frame_left.setStyleSheet("QFrame{\n"
"    background-color: rgb(72,72,73);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton#btn_user, #btn_user_2, #btn_song, #btn_song_2 {\n"
"    background-color: rgb(72,72,73);\n"
"    color: rgb(205, 205, 205);\n"
"    border: 0px;\n"
"}\n"
"QPushButton#btn_user:hover, #btn_user_2:hover, #btn_song:hover, #btn_song_2:hover {\n"
"    background-color: rgb(157, 121, 95);\n"
"}\n"
"QPushButton#btn_user:pressed, #btn_user_2:pressed, #btn_song:pressed, #btn_song_2:pressed {\n"
"    background-color: rgb(130, 100, 78);\n"
"}\n"
"")
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.btn_user = QtWidgets.QPushButton(self.frame_left)
        self.btn_user.setGeometry(QtCore.QRect(0, 0, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_user.setFont(font)
        self.btn_user.setStyleSheet("")
        self.btn_user.setObjectName("btn_user")
        self.btn_user_2 = QtWidgets.QPushButton(self.frame_left)
        self.btn_user_2.setGeometry(QtCore.QRect(0, 40, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_user_2.setFont(font)
        self.btn_user_2.setStyleSheet("")
        self.btn_user_2.setObjectName("btn_user_2")
        self.btn_song = QtWidgets.QPushButton(self.frame_left)
        self.btn_song.setGeometry(QtCore.QRect(0, 80, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_song.setFont(font)
        self.btn_song.setStyleSheet("")
        self.btn_song.setObjectName("btn_song")
        self.btn_song_2 = QtWidgets.QPushButton(self.frame_left)
        self.btn_song_2.setGeometry(QtCore.QRect(0, 120, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_song_2.setFont(font)
        self.btn_song_2.setStyleSheet("")
        self.btn_song_2.setObjectName("btn_song_2")
        self.frame_pages = QtWidgets.QFrame(self.frame)
        self.frame_pages.setGeometry(QtCore.QRect(80, 50, 410, 600))
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 410, 600))
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.stackedWidget.setStyleSheet("QPushButton#btn_ban_id, #btn_reset_id, #btn_online, #btn_search, #btn_add_db, #btn_search_2, #btn_delete {\n"
"    background-color: rgba(157, 121, 95, 255);\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_ban_id:hover , #btn_reset_id:hover, #btn_online:hover, #btn_search:hover, #btn_add_db:hover, #btn_search_2:hover, #btn_delete:hover {\n"
"    background-color: rgba(143, 110, 86, 255);\n"
"}\n"
"QPushButton#btn_ban_id:pressed , #btn_reset_id:pressed, #btn_online:pressed, #btn_search:pressed, #btn_add_db:pressed, #btn_search_2:pressed, #btn_delete:pressed {\n"
"    background-color: rgba(130, 100, 78, 255);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgba(205,205,205,150);\n"
"    color: rgb(72,72,73);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"    padding-bottom: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QTextEdit {\n"
"    background-color: rgba(205,205,205,150);\n"
"    color: rgb(72,72,73);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: rgba(205,205,205,150);\n"
"    color: rgb(72,72,73);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"    padding-bottom: 2px;\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_user = QtWidgets.QWidget()
        self.page_user.setObjectName("page_user")
        self.input_ban_id = QtWidgets.QLineEdit(self.page_user)
        self.input_ban_id.setGeometry(QtCore.QRect(10, 10, 390, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_ban_id.setFont(font)
        self.input_ban_id.setStyleSheet("")
        self.input_ban_id.setObjectName("input_ban_id")
        self.btn_ban_id = QtWidgets.QPushButton(self.page_user)
        self.btn_ban_id.setGeometry(QtCore.QRect(10, 110, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ban_id.setFont(font)
        self.btn_ban_id.setStyleSheet("")
        self.btn_ban_id.setObjectName("btn_ban_id")
        self.label_ban = QtWidgets.QPlainTextEdit(self.page_user)
        self.label_ban.setGeometry(QtCore.QRect(10, 50, 390, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_ban.setFont(font)
        self.label_ban.setStyleSheet("")
        self.label_ban.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_ban.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_ban.setReadOnly(True)
        self.label_ban.setObjectName("label_ban")
        self.input_reset_id = QtWidgets.QLineEdit(self.page_user)
        self.input_reset_id.setGeometry(QtCore.QRect(10, 170, 390, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_reset_id.setFont(font)
        self.input_reset_id.setStyleSheet("")
        self.input_reset_id.setObjectName("input_reset_id")
        self.label_reset = QtWidgets.QPlainTextEdit(self.page_user)
        self.label_reset.setGeometry(QtCore.QRect(10, 210, 390, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_reset.setFont(font)
        self.label_reset.setStyleSheet("")
        self.label_reset.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_reset.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_reset.setReadOnly(True)
        self.label_reset.setObjectName("label_reset")
        self.btn_reset_id = QtWidgets.QPushButton(self.page_user)
        self.btn_reset_id.setGeometry(QtCore.QRect(10, 270, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_reset_id.setFont(font)
        self.btn_reset_id.setStyleSheet("")
        self.btn_reset_id.setObjectName("btn_reset_id")
        self.list_online = QtWidgets.QListWidget(self.page_user)
        self.list_online.setGeometry(QtCore.QRect(10, 330, 390, 231))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.list_online.setFont(font)
        self.list_online.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_online.setStyleSheet("QListWidget#list_online {\n"
"    color: rgb(72,72,73);\n"
"    background-color: rgba(205,205,205,150);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"}\n"
"QListWidget::item:hover {\n"
"    color: rgb(205, 205, 205);\n"
"    background-color: rgba(157, 121, 95, 210);\n"
"}\n"
"QListWidget::item:selected {\n"
"    color: rgb(205, 205, 205);\n"
"    background-color: rgba(157, 121, 95, 255);\n"
"}")
        self.list_online.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_online.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_online.setWordWrap(False)
        self.list_online.setObjectName("list_online")
        self.btn_online = QtWidgets.QPushButton(self.page_user)
        self.btn_online.setGeometry(QtCore.QRect(10, 550, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_online.setFont(font)
        self.btn_online.setStyleSheet("")
        self.btn_online.setObjectName("btn_online")
        self.input_ban_id.raise_()
        self.label_ban.raise_()
        self.btn_ban_id.raise_()
        self.input_reset_id.raise_()
        self.label_reset.raise_()
        self.btn_reset_id.raise_()
        self.list_online.raise_()
        self.btn_online.raise_()
        self.stackedWidget.addWidget(self.page_user)
        self.page_user_2 = QtWidgets.QWidget()
        self.page_user_2.setObjectName("page_user_2")
        self.input_search = QtWidgets.QLineEdit(self.page_user_2)
        self.input_search.setGeometry(QtCore.QRect(10, 10, 390, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_search.setFont(font)
        self.input_search.setStyleSheet("")
        self.input_search.setObjectName("input_search")
        self.btn_search = QtWidgets.QPushButton(self.page_user_2)
        self.btn_search.setGeometry(QtCore.QRect(10, 110, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("")
        self.btn_search.setObjectName("btn_search")
        self.label_search = QtWidgets.QPlainTextEdit(self.page_user_2)
        self.label_search.setGeometry(QtCore.QRect(10, 50, 390, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_search.setFont(font)
        self.label_search.setStyleSheet("")
        self.label_search.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_search.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_search.setReadOnly(True)
        self.label_search.setObjectName("label_search")
        self.input_search.raise_()
        self.label_search.raise_()
        self.btn_search.raise_()
        self.stackedWidget.addWidget(self.page_user_2)
        self.page_song = QtWidgets.QWidget()
        self.page_song.setObjectName("page_song")
        self.input_author = QtWidgets.QLineEdit(self.page_song)
        self.input_author.setGeometry(QtCore.QRect(10, 10, 390, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_author.setFont(font)
        self.input_author.setStyleSheet("")
        self.input_author.setObjectName("input_author")
        self.input_name = QtWidgets.QLineEdit(self.page_song)
        self.input_name.setGeometry(QtCore.QRect(10, 50, 390, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_name.setFont(font)
        self.input_name.setStyleSheet("")
        self.input_name.setText("")
        self.input_name.setObjectName("input_name")
        self.btn_add_db = QtWidgets.QPushButton(self.page_song)
        self.btn_add_db.setGeometry(QtCore.QRect(10, 550, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_db.setFont(font)
        self.btn_add_db.setStyleSheet("")
        self.btn_add_db.setObjectName("btn_add_db")
        self.input_chords = QtWidgets.QTextEdit(self.page_song)
        self.input_chords.setGeometry(QtCore.QRect(10, 90, 390, 451))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_chords.setFont(font)
        self.input_chords.setStyleSheet("")
        self.input_chords.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_chords.setObjectName("input_chords")
        self.stackedWidget.addWidget(self.page_song)
        self.page_song_2 = QtWidgets.QWidget()
        self.page_song_2.setObjectName("page_song_2")
        self.btn_search_2 = QtWidgets.QPushButton(self.page_song_2)
        self.btn_search_2.setGeometry(QtCore.QRect(10, 110, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_search_2.setFont(font)
        self.btn_search_2.setStyleSheet("")
        self.btn_search_2.setObjectName("btn_search_2")
        self.label_search_2 = QtWidgets.QPlainTextEdit(self.page_song_2)
        self.label_search_2.setGeometry(QtCore.QRect(10, 50, 390, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_search_2.setFont(font)
        self.label_search_2.setStyleSheet("")
        self.label_search_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_search_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_search_2.setReadOnly(True)
        self.label_search_2.setObjectName("label_search_2")
        self.input_search_2 = QtWidgets.QLineEdit(self.page_song_2)
        self.input_search_2.setGeometry(QtCore.QRect(10, 10, 390, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_search_2.setFont(font)
        self.input_search_2.setStyleSheet("")
        self.input_search_2.setText("")
        self.input_search_2.setObjectName("input_search_2")
        self.list_search = QtWidgets.QListWidget(self.page_song_2)
        self.list_search.setGeometry(QtCore.QRect(10, 160, 391, 271))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.list_search.setFont(font)
        self.list_search.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.list_search.setStyleSheet("QListWidget#list_search {\n"
"    color: rgb(72,72,73);\n"
"    background-color: rgba(205,205,205,150);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"}\n"
"QListWidget::item:hover {\n"
"    color: rgb(205, 205, 205);\n"
"    background-color: rgba(157, 121, 95, 210);\n"
"}\n"
"QListWidget::item:selected {\n"
"    color: rgb(205, 205, 205);\n"
"    background-color: rgba(157, 121, 95, 255);\n"
"}")
        self.list_search.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_search.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_search.setWordWrap(False)
        self.list_search.setObjectName("list_search")
        self.btn_delete = QtWidgets.QPushButton(self.page_song_2)
        self.btn_delete.setGeometry(QtCore.QRect(10, 550, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete.setFont(font)
        self.btn_delete.setStyleSheet("")
        self.btn_delete.setObjectName("btn_delete")
        self.input_delete = QtWidgets.QLineEdit(self.page_song_2)
        self.input_delete.setGeometry(QtCore.QRect(10, 450, 390, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_delete.setFont(font)
        self.input_delete.setStyleSheet("")
        self.input_delete.setText("")
        self.input_delete.setObjectName("input_delete")
        self.label_delete = QtWidgets.QPlainTextEdit(self.page_song_2)
        self.label_delete.setGeometry(QtCore.QRect(10, 490, 390, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_delete.setFont(font)
        self.label_delete.setStyleSheet("")
        self.label_delete.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_delete.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_delete.setReadOnly(True)
        self.label_delete.setObjectName("label_delete")
        self.label_search_2.raise_()
        self.input_search_2.raise_()
        self.list_search.raise_()
        self.input_delete.raise_()
        self.label_delete.raise_()
        self.btn_search_2.raise_()
        self.btn_delete.raise_()
        self.stackedWidget.addWidget(self.page_song_2)
        self.page_empty = QtWidgets.QWidget()
        self.page_empty.setObjectName("page_empty")
        self.stackedWidget.addWidget(self.page_empty)
        self.frame_bg = QtWidgets.QFrame(self.frame)
        self.frame_bg.setGeometry(QtCore.QRect(0, 0, 490, 650))
        self.frame_bg.setStyleSheet("")
        self.frame_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg.setObjectName("frame_bg")
        self.label_bg = QtWidgets.QLabel(self.frame_bg)
        self.label_bg.setGeometry(QtCore.QRect(0, 0, 490, 650))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bg.setFont(font)
        self.label_bg.setStyleSheet("border-image: url(:/images/images/bg.jpg);")
        self.label_bg.setText("")
        self.label_bg.setObjectName("label_bg")
        self.frame_bg.raise_()
        self.frame_pages.raise_()
        self.frame_top.raise_()
        self.frame_left.raise_()
        AdminScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminScreen)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(AdminScreen)

    def retranslateUi(self, AdminScreen):
        _translate = QtCore.QCoreApplication.translate
        AdminScreen.setWindowTitle(_translate("AdminScreen", "MainWindow"))
        self.btn_exit.setText(_translate("AdminScreen", "EXIT"))
        self.btn_toggle.setText(_translate("AdminScreen", " >"))
        self.label_name.setText(_translate("AdminScreen", "GUITAR AIO - Admin panel"))
        self.btn_user.setText(_translate("AdminScreen", "USERS #1"))
        self.btn_user_2.setText(_translate("AdminScreen", "USERS #2"))
        self.btn_song.setText(_translate("AdminScreen", "SONGS #1"))
        self.btn_song_2.setText(_translate("AdminScreen", "SONGS #2"))
        self.input_ban_id.setPlaceholderText(_translate("AdminScreen", "User ID"))
        self.btn_ban_id.setText(_translate("AdminScreen", "DELETE USER"))
        self.label_ban.setPlainText(_translate("AdminScreen", "Use button below to delete user\'s account from database.\n"
"He can register again later."))
        self.input_reset_id.setPlaceholderText(_translate("AdminScreen", "User ID"))
        self.label_reset.setPlainText(_translate("AdminScreen", "Use button below to reset user\'s stats."))
        self.btn_reset_id.setText(_translate("AdminScreen", "RESET STATS"))
        self.btn_online.setText(_translate("AdminScreen", "ONLINE USERS (refresh)"))
        self.input_search.setPlaceholderText(_translate("AdminScreen", "Username"))
        self.btn_search.setText(_translate("AdminScreen", "SEARCH"))
        self.label_search.setPlainText(_translate("AdminScreen", "Use button below to find user\'s ID using their username."))
        self.input_author.setPlaceholderText(_translate("AdminScreen", "Song author"))
        self.input_name.setPlaceholderText(_translate("AdminScreen", "Song name"))
        self.btn_add_db.setText(_translate("AdminScreen", "ADD SONG TO DB"))
        self.input_chords.setPlaceholderText(_translate("AdminScreen", "Chords"))
        self.btn_search_2.setText(_translate("AdminScreen", "SEARCH"))
        self.label_search_2.setPlainText(_translate("AdminScreen", "Use button below to search for song from DB using song\'s name."))
        self.input_search_2.setPlaceholderText(_translate("AdminScreen", "Song name/author"))
        self.btn_delete.setText(_translate("AdminScreen", "DELETE"))
        self.input_delete.setPlaceholderText(_translate("AdminScreen", "Song ID"))
        self.label_delete.setPlainText(_translate("AdminScreen", "Use button below to delete song from DB.\n"
"You can add it later again."))
import res_rc
