# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadingScreen(object):
    def setupUi(self, LoadingScreen):
        LoadingScreen.setObjectName("LoadingScreen")
        LoadingScreen.resize(490, 220)
        self.centralwidget = QtWidgets.QWidget(LoadingScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 490, 220))
        self.frame.setStyleSheet("QFrame {    \n"
"    background-color: rgb(205, 205, 205);    \n"
"    color: rgb(220, 220, 220);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_description = QtWidgets.QLabel(self.frame)
        self.label_description.setGeometry(QtCore.QRect(0, 80, 490, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai Light")
        font.setPointSize(14)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(172, 144, 124);")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.label_title = QtWidgets.QLabel(self.frame)
        self.label_title.setGeometry(QtCore.QRect(0, 15, 490, 71))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(42)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(157, 121, 95);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(50, 140, 390, 23))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(150, 148, 147);\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(157, 121, 95, 255), stop:1 rgba(118, 91, 71, 255));\n"
"}")
        self.progressBar.setProperty("value", 68)
        self.progressBar.setObjectName("progressBar")
        self.label_credits = QtWidgets.QLabel(self.frame)
        self.label_credits.setGeometry(QtCore.QRect(10, 195, 420, 21))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(157, 121, 95);")
        self.label_credits.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.label_loading = QtWidgets.QLabel(self.frame)
        self.label_loading.setGeometry(QtCore.QRect(50, 165, 390, 21))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(172, 144, 124);")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        LoadingScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoadingScreen)
        QtCore.QMetaObject.connectSlotsByName(LoadingScreen)

    def retranslateUi(self, LoadingScreen):
        _translate = QtCore.QCoreApplication.translate
        LoadingScreen.setWindowTitle(_translate("LoadingScreen", "MainWindow"))
        self.label_description.setText(_translate("LoadingScreen", "<html><head/><body><p>LETS PRACTICE TOGETHER</p></body></html>"))
        self.label_title.setText(_translate("LoadingScreen", "<html><head/><body><p><span style=\" font-weight:600;\">GUITAR</span> AIO</p></body></html>"))
        self.label_credits.setText(_translate("LoadingScreen", "<html><head/><body><p><span style=\" font-weight:600;\">Created</span>: Sule (2021)</p></body></html>"))
        self.label_loading.setText(_translate("LoadingScreen", "loading..."))
