# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsScreen(object):
    def setupUi(self, SettingsScreen):
        SettingsScreen.setObjectName("SettingsScreen")
        SettingsScreen.resize(490, 650)
        SettingsScreen.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(SettingsScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 490, 650))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_top = QtWidgets.QFrame(self.frame)
        self.frame_top.setGeometry(QtCore.QRect(0, 0, 490, 50))
        self.frame_top.setStyleSheet("QFrame{\n"
"    background-color: rgb(72,72,73);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton#btn_toggle, #btn_exit {\n"
"    background-color: rgb(157, 121, 95);\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_toggle:hover, #btn_exit:hover {\n"
"    background-color: rgb(143, 110, 86);\n"
"}\n"
"QPushButton#btn_toggle:pressed, #btn_exit:pressed {\n"
"    background-color: rgb(130, 100, 78);\n"
"}\n"
"")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.btn_exit = QtWidgets.QPushButton(self.frame_top)
        self.btn_exit.setGeometry(QtCore.QRect(420, 10, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_top)
        self.btn_toggle.setGeometry(QtCore.QRect(10, 10, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_toggle.setFont(font)
        self.btn_toggle.setStyleSheet("")
        self.btn_toggle.setObjectName("btn_toggle")
        self.label = QtWidgets.QLabel(self.frame_top)
        self.label.setGeometry(QtCore.QRect(80, -24, 100, 100))
        self.label.setStyleSheet("border-image: url(:/images/images/logo.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_name = QtWidgets.QLabel(self.frame_top)
        self.label_name.setGeometry(QtCore.QRect(80, 13, 331, 50))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color: rgb(205,205,205);\n"
"background-color: rgba(0,0,0,0);")
        self.label_name.setObjectName("label_name")
        self.frame_left = QtWidgets.QFrame(self.frame)
        self.frame_left.setGeometry(QtCore.QRect(0, 50, 80, 600))
        self.frame_left.setStyleSheet("QFrame{\n"
"    background-color: rgb(72,72,73);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton#btn_acc, #btn_keys {\n"
"    background-color: rgb(72,72,73);\n"
"    color: rgb(205, 205, 205);\n"
"    border: 0px;\n"
"}\n"
"QPushButton#btn_acc:hover, #btn_keys:hover {\n"
"    background-color: rgb(157, 121, 95);\n"
"}\n"
"QPushButton#btn_acc:pressed, #btn_keys:pressed {\n"
"    background-color: rgba(130, 100, 78, 255);\n"
"}\n"
"")
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.btn_acc = QtWidgets.QPushButton(self.frame_left)
        self.btn_acc.setGeometry(QtCore.QRect(0, 0, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_acc.setFont(font)
        self.btn_acc.setStyleSheet("")
        self.btn_acc.setObjectName("btn_acc")
        self.btn_keys = QtWidgets.QPushButton(self.frame_left)
        self.btn_keys.setGeometry(QtCore.QRect(0, 40, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_keys.setFont(font)
        self.btn_keys.setStyleSheet("")
        self.btn_keys.setObjectName("btn_keys")
        self.frame_pages = QtWidgets.QFrame(self.frame)
        self.frame_pages.setGeometry(QtCore.QRect(80, 50, 410, 600))
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 410, 600))
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.stackedWidget.setStyleSheet("QPushButton#btn_ch_email, #btn_ch_name, #btn_ch_pw{\n"
"    background-color: rgba(157, 121, 95, 255);\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_ch_email:hover, #btn_ch_name:hover, #btn_ch_pw:hover {\n"
"    background-color: rgba(143, 110, 86, 255);\n"
"}\n"
"QPushButton#btn_ch_email:pressed, #btn_ch_name:pressed, #btn_ch_pw:pressed {\n"
"    background-color: rgba(130, 100, 78, 255);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgba(205,205,205,150);\n"
"    color: rgb(72,72,73);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"    padding-bottom: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: rgba(205,205,205,150);\n"
"    color: rgb(72,72,73);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(157, 121, 95, 255);\n"
"    padding-bottom: 2px;\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_acc = QtWidgets.QWidget()
        self.page_acc.setObjectName("page_acc")
        self.btn_ch_name = QtWidgets.QPushButton(self.page_acc)
        self.btn_ch_name.setGeometry(QtCore.QRect(10, 110, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ch_name.setFont(font)
        self.btn_ch_name.setStyleSheet("")
        self.btn_ch_name.setObjectName("btn_ch_name")
        self.input_first = QtWidgets.QLineEdit(self.page_acc)
        self.input_first.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_first.setFont(font)
        self.input_first.setStyleSheet("")
        self.input_first.setObjectName("input_first")
        self.label_name_2 = QtWidgets.QPlainTextEdit(self.page_acc)
        self.label_name_2.setGeometry(QtCore.QRect(10, 50, 390, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_name_2.setFont(font)
        self.label_name_2.setStyleSheet("")
        self.label_name_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_name_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_name_2.setReadOnly(True)
        self.label_name_2.setObjectName("label_name_2")
        self.label_email = QtWidgets.QPlainTextEdit(self.page_acc)
        self.label_email.setGeometry(QtCore.QRect(10, 210, 390, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_email.setFont(font)
        self.label_email.setStyleSheet("")
        self.label_email.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_email.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_email.setReadOnly(True)
        self.label_email.setObjectName("label_email")
        self.btn_ch_email = QtWidgets.QPushButton(self.page_acc)
        self.btn_ch_email.setGeometry(QtCore.QRect(10, 270, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ch_email.setFont(font)
        self.btn_ch_email.setStyleSheet("")
        self.btn_ch_email.setObjectName("btn_ch_email")
        self.input_email = QtWidgets.QLineEdit(self.page_acc)
        self.input_email.setGeometry(QtCore.QRect(10, 170, 390, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_email.setFont(font)
        self.input_email.setStyleSheet("")
        self.input_email.setObjectName("input_email")
        self.input_last = QtWidgets.QLineEdit(self.page_acc)
        self.input_last.setGeometry(QtCore.QRect(210, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_last.setFont(font)
        self.input_last.setStyleSheet("")
        self.input_last.setObjectName("input_last")
        self.btn_ch_pw = QtWidgets.QPushButton(self.page_acc)
        self.btn_ch_pw.setGeometry(QtCore.QRect(10, 430, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ch_pw.setFont(font)
        self.btn_ch_pw.setStyleSheet("")
        self.btn_ch_pw.setObjectName("btn_ch_pw")
        self.label_pw = QtWidgets.QPlainTextEdit(self.page_acc)
        self.label_pw.setGeometry(QtCore.QRect(10, 370, 390, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_pw.setFont(font)
        self.label_pw.setStyleSheet("")
        self.label_pw.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_pw.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_pw.setReadOnly(True)
        self.label_pw.setObjectName("label_pw")
        self.input_pw = QtWidgets.QLineEdit(self.page_acc)
        self.input_pw.setGeometry(QtCore.QRect(10, 330, 390, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.input_pw.setFont(font)
        self.input_pw.setStyleSheet("")
        self.input_pw.setObjectName("input_pw")
        self.input_first.raise_()
        self.label_name_2.raise_()
        self.btn_ch_name.raise_()
        self.label_email.raise_()
        self.btn_ch_email.raise_()
        self.input_email.raise_()
        self.input_last.raise_()
        self.label_pw.raise_()
        self.input_pw.raise_()
        self.btn_ch_pw.raise_()
        self.stackedWidget.addWidget(self.page_acc)
        self.page_keys = QtWidgets.QWidget()
        self.page_keys.setObjectName("page_keys")
        self.stackedWidget.addWidget(self.page_keys)
        self.page_empty = QtWidgets.QWidget()
        self.page_empty.setObjectName("page_empty")
        self.stackedWidget.addWidget(self.page_empty)
        self.frame_bg = QtWidgets.QFrame(self.frame)
        self.frame_bg.setGeometry(QtCore.QRect(0, 0, 490, 650))
        self.frame_bg.setStyleSheet("")
        self.frame_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg.setObjectName("frame_bg")
        self.label_bg = QtWidgets.QLabel(self.frame_bg)
        self.label_bg.setGeometry(QtCore.QRect(0, 0, 490, 650))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bg.setFont(font)
        self.label_bg.setStyleSheet("border-image: url(:/images/images/bg.jpg);")
        self.label_bg.setText("")
        self.label_bg.setObjectName("label_bg")
        self.frame_bg.raise_()
        self.frame_pages.raise_()
        self.frame_top.raise_()
        self.frame_left.raise_()
        SettingsScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingsScreen)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingsScreen)

    def retranslateUi(self, SettingsScreen):
        _translate = QtCore.QCoreApplication.translate
        SettingsScreen.setWindowTitle(_translate("SettingsScreen", "MainWindow"))
        self.btn_exit.setText(_translate("SettingsScreen", "EXIT"))
        self.btn_toggle.setText(_translate("SettingsScreen", " >"))
        self.label_name.setText(_translate("SettingsScreen", "GUITAR AIO - Settings"))
        self.btn_acc.setText(_translate("SettingsScreen", "ACCOUNT"))
        self.btn_keys.setText(_translate("SettingsScreen", "KEYS"))
        self.btn_ch_name.setText(_translate("SettingsScreen", "CHANGE"))
        self.input_first.setPlaceholderText(_translate("SettingsScreen", "New first name"))
        self.label_name_2.setPlainText(_translate("SettingsScreen", "Use button below to change your name.\n"
"You can change it again later."))
        self.label_email.setPlainText(_translate("SettingsScreen", "Use button below to change your email.\n"
"You can change it again later."))
        self.btn_ch_email.setText(_translate("SettingsScreen", "CHANGE"))
        self.input_email.setPlaceholderText(_translate("SettingsScreen", "New email"))
        self.input_last.setPlaceholderText(_translate("SettingsScreen", "New last name"))
        self.btn_ch_pw.setText(_translate("SettingsScreen", "CHANGE"))
        self.label_pw.setPlainText(_translate("SettingsScreen", "Use button below to change your password.\n"
"You can change it again later."))
        self.input_pw.setPlaceholderText(_translate("SettingsScreen", "New password"))
import res_rc
