# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeScreen(object):
    def setupUi(self, WelcomeScreen):
        WelcomeScreen.setObjectName("WelcomeScreen")
        WelcomeScreen.resize(490, 400)
        self.centralwidget = QtWidgets.QWidget(WelcomeScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 490, 400))
        self.frame.setStyleSheet("QPushButton#btn_fb, #btn_ig, #btn_yt, #btn_in, #btn_git {\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: rgb(157, 121, 95);\n"
"}\n"
"\n"
"QPushButton#btn_login, #btn_switch, #btn_register {\n"
"    background-color: rgb(157, 121, 95);\n"
"    color: rgb(205,205,205);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_login:hover, #btn_switch:hover, #btn_register:hover {\n"
"    background-color: rgb(130, 100, 78);\n"
"}\n"
"QPushButton#btn_login:pressed, #btn_switch:pressed, #btn_register:pressed {\n"
"    background-color: rgb(118, 91, 71);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stacked_pages = QtWidgets.QStackedWidget(self.frame)
        self.stacked_pages.setGeometry(QtCore.QRect(0, 0, 490, 400))
        self.stacked_pages.setStyleSheet("QStackedWidget#stacked_pages {\n"
"    background-color: rgb(205, 205, 205);\n"
"}")
        self.stacked_pages.setObjectName("stacked_pages")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.label_bg = QtWidgets.QLabel(self.page_login)
        self.label_bg.setGeometry(QtCore.QRect(0, 0, 245, 400))
        self.label_bg.setStyleSheet("border-image: url(:/images/images/bg.jpg);")
        self.label_bg.setText("")
        self.label_bg.setObjectName("label_bg")
        self.label_bg_3 = QtWidgets.QLabel(self.page_login)
        self.label_bg_3.setGeometry(QtCore.QRect(0, 50, 245, 170))
        self.label_bg_3.setStyleSheet("background-color: rgba(0,0,0,75);\n"
"border-radius:0px;\n"
"")
        self.label_bg_3.setText("")
        self.label_bg_3.setObjectName("label_bg_3")
        self.label_desc = QtWidgets.QLabel(self.page_login)
        self.label_desc.setGeometry(QtCore.QRect(10, 80, 201, 111))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_desc.setFont(font)
        self.label_desc.setStyleSheet("color: rgba(255,255,255,200);\n"
"background-color: rgba(0,0,0,0);")
        self.label_desc.setObjectName("label_desc")
        self.label_credits = QtWidgets.QLabel(self.page_login)
        self.label_credits.setGeometry(QtCore.QRect(10, 195, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgba(255,255,255,200);\n"
"background-color: rgba(0,0,0,0);")
        self.label_credits.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.label_name = QtWidgets.QLabel(self.page_login)
        self.label_name.setGeometry(QtCore.QRect(10, 50, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color: rgba(255,255,255,200);\n"
"background-color: rgba(0,0,0,0);")
        self.label_name.setObjectName("label_name")
        self.label_login = QtWidgets.QLabel(self.page_login)
        self.label_login.setGeometry(QtCore.QRect(245, 35, 245, 60))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("color: rgb(157, 121, 95);")
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.input_name = QtWidgets.QLineEdit(self.page_login)
        self.input_name.setGeometry(QtCore.QRect(270, 100, 195, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_name.setFont(font)
        self.input_name.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(157, 121, 95, 255);\n"
"color: rgba(157, 121, 95, 255);\n"
"padding-bottom: 7px;")
        self.input_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_name.setObjectName("input_name")
        self.input_pw = QtWidgets.QLineEdit(self.page_login)
        self.input_pw.setGeometry(QtCore.QRect(270, 150, 195, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_pw.setFont(font)
        self.input_pw.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(157, 121, 95, 255);\n"
"color: rgba(157, 121, 95, 255);\n"
"padding-bottom: 7px;")
        self.input_pw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_pw.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_pw.setObjectName("input_pw")
        self.btn_login = QtWidgets.QPushButton(self.page_login)
        self.btn_login.setGeometry(QtCore.QRect(270, 300, 195, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("")
        self.btn_login.setObjectName("btn_login")
        self.label_bg_2 = QtWidgets.QLabel(self.page_login)
        self.label_bg_2.setGeometry(QtCore.QRect(0, 0, 245, 400))
        self.label_bg_2.setStyleSheet("background-color: rgba(0,0,0,25);")
        self.label_bg_2.setText("")
        self.label_bg_2.setObjectName("label_bg_2")
        self.label_bg.raise_()
        self.label_bg_2.raise_()
        self.label_bg_3.raise_()
        self.label_desc.raise_()
        self.label_credits.raise_()
        self.label_name.raise_()
        self.label_login.raise_()
        self.input_name.raise_()
        self.input_pw.raise_()
        self.btn_login.raise_()
        self.stacked_pages.addWidget(self.page_login)
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.label_bg_4 = QtWidgets.QLabel(self.page_register)
        self.label_bg_4.setGeometry(QtCore.QRect(245, 0, 245, 400))
        self.label_bg_4.setStyleSheet("border-image: url(:/images/images/bg_flipped.jpg);")
        self.label_bg_4.setText("")
        self.label_bg_4.setObjectName("label_bg_4")
        self.btn_register = QtWidgets.QPushButton(self.page_register)
        self.btn_register.setGeometry(QtCore.QRect(25, 300, 195, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("")
        self.btn_register.setObjectName("btn_register")
        self.input_pw_3 = QtWidgets.QLineEdit(self.page_register)
        self.input_pw_3.setGeometry(QtCore.QRect(25, 250, 195, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_pw_3.setFont(font)
        self.input_pw_3.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(157, 121, 95, 255);\n"
"color: rgba(157, 121, 95, 255);\n"
"padding-bottom: 7px;")
        self.input_pw_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_pw_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_pw_3.setObjectName("input_pw_3")
        self.input_pw_2 = QtWidgets.QLineEdit(self.page_register)
        self.input_pw_2.setGeometry(QtCore.QRect(25, 200, 195, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_pw_2.setFont(font)
        self.input_pw_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(157, 121, 95, 255);\n"
"color: rgba(157, 121, 95, 255);\n"
"padding-bottom: 7px;")
        self.input_pw_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_pw_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_pw_2.setObjectName("input_pw_2")
        self.input_email = QtWidgets.QLineEdit(self.page_register)
        self.input_email.setGeometry(QtCore.QRect(25, 150, 195, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_email.setFont(font)
        self.input_email.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(157, 121, 95, 255);\n"
"color: rgba(157, 121, 95, 255);\n"
"padding-bottom: 7px;")
        self.input_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_email.setObjectName("input_email")
        self.input_first = QtWidgets.QLineEdit(self.page_register)
        self.input_first.setGeometry(QtCore.QRect(25, 100, 95, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_first.setFont(font)
        self.input_first.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(157, 121, 95, 255);\n"
"color: rgba(157, 121, 95, 255);\n"
"padding-bottom: 7px;")
        self.input_first.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_first.setObjectName("input_first")
        self.input_last = QtWidgets.QLineEdit(self.page_register)
        self.input_last.setGeometry(QtCore.QRect(125, 100, 95, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_last.setFont(font)
        self.input_last.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(157, 121, 95, 255);\n"
"color: rgba(157, 121, 95, 255);\n"
"padding-bottom: 7px;")
        self.input_last.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_last.setObjectName("input_last")
        self.label_register = QtWidgets.QLabel(self.page_register)
        self.label_register.setGeometry(QtCore.QRect(0, 35, 245, 60))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_register.setFont(font)
        self.label_register.setStyleSheet("color: rgb(157, 121, 95);")
        self.label_register.setAlignment(QtCore.Qt.AlignCenter)
        self.label_register.setObjectName("label_register")
        self.label_bg_6 = QtWidgets.QLabel(self.page_register)
        self.label_bg_6.setGeometry(QtCore.QRect(245, 50, 245, 170))
        self.label_bg_6.setStyleSheet("background-color: rgba(0,0,0,75);\n"
"border-radius:0px;\n"
"")
        self.label_bg_6.setText("")
        self.label_bg_6.setObjectName("label_bg_6")
        self.label_credits_2 = QtWidgets.QLabel(self.page_register)
        self.label_credits_2.setGeometry(QtCore.QRect(270, 195, 210, 21))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.label_credits_2.setFont(font)
        self.label_credits_2.setStyleSheet("color: rgba(255,255,255,200);\n"
"background-color: rgba(0,0,0,0);")
        self.label_credits_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits_2.setObjectName("label_credits_2")
        self.label_name_2 = QtWidgets.QLabel(self.page_register)
        self.label_name_2.setGeometry(QtCore.QRect(300, 50, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_name_2.setFont(font)
        self.label_name_2.setStyleSheet("color: rgba(255,255,255,200);\n"
"background-color: rgba(0,0,0,0);")
        self.label_name_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_name_2.setObjectName("label_name_2")
        self.label_desc_2 = QtWidgets.QLabel(self.page_register)
        self.label_desc_2.setGeometry(QtCore.QRect(280, 80, 200, 109))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_desc_2.setFont(font)
        self.label_desc_2.setStyleSheet("color: rgba(255,255,255,200);\n"
"background-color: rgba(0,0,0,0);")
        self.label_desc_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_desc_2.setObjectName("label_desc_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page_register)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 350, 231, 41))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.grid_social = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.grid_social.setContentsMargins(0, 0, 0, 0)
        self.grid_social.setSpacing(0)
        self.grid_social.setObjectName("grid_social")
        self.btn_fb = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_fb.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.btn_fb.setFont(font)
        self.btn_fb.setStyleSheet("")
        self.btn_fb.setObjectName("btn_fb")
        self.grid_social.addWidget(self.btn_fb, 0, 0, 1, 1)
        self.btn_ig = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_ig.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.btn_ig.setFont(font)
        self.btn_ig.setObjectName("btn_ig")
        self.grid_social.addWidget(self.btn_ig, 0, 1, 1, 1)
        self.btn_in = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_in.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.btn_in.setFont(font)
        self.btn_in.setObjectName("btn_in")
        self.grid_social.addWidget(self.btn_in, 0, 3, 1, 1)
        self.btn_yt = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_yt.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.btn_yt.setFont(font)
        self.btn_yt.setObjectName("btn_yt")
        self.grid_social.addWidget(self.btn_yt, 0, 2, 1, 1)
        self.btn_git = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_git.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.btn_git.setFont(font)
        self.btn_git.setObjectName("btn_git")
        self.grid_social.addWidget(self.btn_git, 0, 4, 1, 1)
        self.label_bg_5 = QtWidgets.QLabel(self.page_register)
        self.label_bg_5.setGeometry(QtCore.QRect(245, 0, 245, 400))
        self.label_bg_5.setStyleSheet("background-color: rgba(0,0,0,25);")
        self.label_bg_5.setText("")
        self.label_bg_5.setObjectName("label_bg_5")
        self.label_bg_4.raise_()
        self.label_bg_5.raise_()
        self.btn_register.raise_()
        self.input_pw_3.raise_()
        self.input_pw_2.raise_()
        self.input_email.raise_()
        self.input_first.raise_()
        self.input_last.raise_()
        self.label_register.raise_()
        self.label_bg_6.raise_()
        self.label_credits_2.raise_()
        self.label_name_2.raise_()
        self.label_desc_2.raise_()
        self.gridLayoutWidget_3.raise_()
        self.stacked_pages.addWidget(self.page_register)
        self.btn_switch = QtWidgets.QPushButton(self.frame)
        self.btn_switch.setGeometry(QtCore.QRect(230, 50, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_switch.setFont(font)
        self.btn_switch.setStyleSheet("border-radius:10px;")
        self.btn_switch.setObjectName("btn_switch")
        WelcomeScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(WelcomeScreen)
        self.stacked_pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WelcomeScreen)

    def retranslateUi(self, WelcomeScreen):
        _translate = QtCore.QCoreApplication.translate
        WelcomeScreen.setWindowTitle(_translate("WelcomeScreen", "MainWindow"))
        self.label_desc.setText(_translate("WelcomeScreen", "Lorem ipsum dolor sit amet,\n"
"consectetur adipiscing elit,\n"
"sed do eiusmod tempor\n"
"incididunt ut labore et dolore\n"
"magna aliqua"))
        self.label_credits.setText(_translate("WelcomeScreen", "<html><head/><body><p><span style=\" font-weight:600;\">Created</span>: Sule (2020-2021)</p></body></html>"))
        self.label_name.setText(_translate("WelcomeScreen", "Guitar AIO"))
        self.label_login.setText(_translate("WelcomeScreen", "<html><head/><body><p>SIGN IN <span style=\" font-weight:400;\">PAGE</span></p></body></html>"))
        self.input_name.setPlaceholderText(_translate("WelcomeScreen", "Username"))
        self.input_pw.setPlaceholderText(_translate("WelcomeScreen", "Password"))
        self.btn_login.setText(_translate("WelcomeScreen", "LOGIN"))
        self.btn_register.setText(_translate("WelcomeScreen", "REGISTER"))
        self.input_pw_3.setPlaceholderText(_translate("WelcomeScreen", "Confirm password"))
        self.input_pw_2.setPlaceholderText(_translate("WelcomeScreen", "Password"))
        self.input_email.setPlaceholderText(_translate("WelcomeScreen", "Username"))
        self.input_first.setPlaceholderText(_translate("WelcomeScreen", "First Name"))
        self.input_last.setPlaceholderText(_translate("WelcomeScreen", "Last Name"))
        self.label_register.setText(_translate("WelcomeScreen", "<html><head/><body><p>SIGN UP <span style=\" font-weight:400;\">PAGE</span></p></body></html>"))
        self.label_credits_2.setText(_translate("WelcomeScreen", "<html><head/><body><p><span style=\" font-weight:600;\">Created</span>: Sule (2020-2021)</p></body></html>"))
        self.label_name_2.setText(_translate("WelcomeScreen", "Guitar AIO"))
        self.label_desc_2.setText(_translate("WelcomeScreen", "Lorem ipsum dolor sit amet,\n"
"consectetur adipiscing elit,\n"
"sed do eiusmod tempor\n"
"incididunt ut labore et dolore\n"
"magna aliqua"))
        self.btn_fb.setText(_translate("WelcomeScreen", "E"))
        self.btn_ig.setText(_translate("WelcomeScreen", "Q"))
        self.btn_in.setText(_translate("WelcomeScreen", "C"))
        self.btn_yt.setText(_translate("WelcomeScreen", "M"))
        self.btn_git.setText(_translate("WelcomeScreen", ")"))
        self.btn_switch.setText(_translate("WelcomeScreen", ">"))
import res_rc
