# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_practice.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PracticeScreen(object):
    def setupUi(self, PracticeScreen):
        PracticeScreen.setObjectName("PracticeScreen")
        PracticeScreen.resize(890, 650)
        PracticeScreen.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(PracticeScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 890, 650))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget_left = QtWidgets.QWidget(self.frame)
        self.widget_left.setGeometry(QtCore.QRect(0, 50, 200, 550))
        self.widget_left.setStyleSheet("QWidget {\n"
"    background-color:rgb(72,72,73);\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"}")
        self.widget_left.setObjectName("widget_left")
        self.list_songs = QtWidgets.QListWidget(self.widget_left)
        self.list_songs.setGeometry(QtCore.QRect(0, 20, 200, 510))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.list_songs.setFont(font)
        self.list_songs.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.list_songs.setStyleSheet("QListWidget#list_songs {\n"
"    color: rgb(205,205,205);\n"
"    background-color:rgba(0,0,0,0);\n"
"    border-radius: 0px;\n"
"}\n"
"QListWidget::item:hover {\n"
"    color: rgb(205, 205, 205);\n"
"    background-color: rgba(157, 121, 95, 210);\n"
"}\n"
"QListWidget::item:selected {\n"
"    color: rgb(205, 205, 205);\n"
"    background-color: rgba(157, 121, 95, 255);\n"
"}")
        self.list_songs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_songs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_songs.setTextElideMode(QtCore.Qt.ElideNone)
        self.list_songs.setFlow(QtWidgets.QListView.TopToBottom)
        self.list_songs.setViewMode(QtWidgets.QListView.ListMode)
        self.list_songs.setSelectionRectVisible(False)
        self.list_songs.setObjectName("list_songs")
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        self.widget_mid = QtWidgets.QWidget(self.frame)
        self.widget_mid.setGeometry(QtCore.QRect(200, 0, 490, 650))
        self.widget_mid.setStyleSheet("QWidget#widget_mid{\n"
"    background-color:rgb(205,205,205);\n"
"    border: 5px solid rgb(157, 121, 95);\n"
"    border-radius: 5px;\n"
"}\n"
"QLabel{\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.widget_mid.setObjectName("widget_mid")
        self.label_author = QtWidgets.QLabel(self.widget_mid)
        self.label_author.setGeometry(QtCore.QRect(13, 10, 450, 50))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_author.setFont(font)
        self.label_author.setStyleSheet("color: rgb(72,72,73);\n"
"background-color: rgba(0,0,0,0);\n"
"")
        self.label_author.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_author.setObjectName("label_author")
        self.label_name = QtWidgets.QLabel(self.widget_mid)
        self.label_name.setGeometry(QtCore.QRect(15, 47, 450, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color: rgb(72,72,73);\n"
"background-color: rgba(0,0,0,0);")
        self.label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.text_chords = QtWidgets.QPlainTextEdit(self.widget_mid)
        self.text_chords.setGeometry(QtCore.QRect(10, 70, 470, 572))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.text_chords.setFont(font)
        self.text_chords.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: rgb(72,72,73);\n"
"border: none;")
        self.text_chords.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_chords.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.text_chords.setReadOnly(True)
        self.text_chords.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.text_chords.setBackgroundVisible(False)
        self.text_chords.setObjectName("text_chords")
        self.bg = QtWidgets.QLabel(self.widget_mid)
        self.bg.setGeometry(QtCore.QRect(215, 287, 270, 358))
        self.bg.setStyleSheet("border-image: url(:/images/images/bg.jpg);")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.label_author.raise_()
        self.label_name.raise_()
        self.bg.raise_()
        self.text_chords.raise_()
        self.widget_right = QtWidgets.QWidget(self.frame)
        self.widget_right.setGeometry(QtCore.QRect(690, 50, 91, 550))
        self.widget_right.setStyleSheet("QWidget#widget_right {\n"
"    background-color:rgb(72,72,73);\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(205,205,205);\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QPushButton#btn_start, #btn_pause, #btn_finish, #btn_next, #btn_exit {\n"
"    background-color: rgba(157, 121, 95, 255);\n"
"    color: rgb(205,205,205);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_start:hover, #btn_pause:hover, #btn_finish:hover, #btn_next:hover, #btn_exit:hover {\n"
"    background-color: rgba(143, 110, 86, 255);\n"
"}\n"
"QPushButton#btn_start:pressed, #btn_pause:pressed, #btn_finish:pressed, #btn_next:pressed, #btn_exit:pressed {\n"
"    background-color: rgba(130, 100, 78, 255);\n"
"}")
        self.widget_right.setObjectName("widget_right")
        self.btn_start = QtWidgets.QPushButton(self.widget_right)
        self.btn_start.setGeometry(QtCore.QRect(10, 30, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setStyleSheet("border-image: url(:/practice/images/practice/play.jpg);")
        self.btn_start.setText("")
        self.btn_start.setObjectName("btn_start")
        self.btn_pause = QtWidgets.QPushButton(self.widget_right)
        self.btn_pause.setGeometry(QtCore.QRect(10, 100, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_pause.setFont(font)
        self.btn_pause.setStyleSheet("border-image: url(:/practice/images/practice/pause.jpg);")
        self.btn_pause.setText("")
        self.btn_pause.setObjectName("btn_pause")
        self.btn_finish = QtWidgets.QPushButton(self.widget_right)
        self.btn_finish.setGeometry(QtCore.QRect(10, 170, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_finish.setFont(font)
        self.btn_finish.setStyleSheet("border-image: url(:/practice/images/practice/finish.jpg);")
        self.btn_finish.setText("")
        self.btn_finish.setObjectName("btn_finish")
        self.btn_next = QtWidgets.QPushButton(self.widget_right)
        self.btn_next.setGeometry(QtCore.QRect(10, 240, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_next.setFont(font)
        self.btn_next.setStyleSheet("border-image: url(:/practice/images/practice/next.jpg);")
        self.btn_next.setText("")
        self.btn_next.setObjectName("btn_next")
        self.btn_exit = QtWidgets.QPushButton(self.widget_right)
        self.btn_exit.setGeometry(QtCore.QRect(10, 450, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("border-image: url(:/practice/images/practice/exit.jpg);")
        self.btn_exit.setText("")
        self.btn_exit.setObjectName("btn_exit")
        self.label_time = QtWidgets.QLabel(self.widget_right)
        self.label_time.setGeometry(QtCore.QRect(10, 310, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("border-image: url(:/practice/images/practice/count.jpg);")
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.label_songs = QtWidgets.QLabel(self.widget_right)
        self.label_songs.setGeometry(QtCore.QRect(10, 380, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_songs.setFont(font)
        self.label_songs.setStyleSheet("border-image: url(:/practice/images/practice/count.jpg);")
        self.label_songs.setAlignment(QtCore.Qt.AlignCenter)
        self.label_songs.setObjectName("label_songs")
        self.btn_start.raise_()
        self.btn_pause.raise_()
        self.btn_finish.raise_()
        self.btn_exit.raise_()
        self.label_time.raise_()
        self.btn_next.raise_()
        self.label_songs.raise_()
        self.widget_mid.raise_()
        self.widget_right.raise_()
        self.widget_left.raise_()
        PracticeScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(PracticeScreen)
        QtCore.QMetaObject.connectSlotsByName(PracticeScreen)

    def retranslateUi(self, PracticeScreen):
        _translate = QtCore.QCoreApplication.translate
        PracticeScreen.setWindowTitle(_translate("PracticeScreen", "MainWindow"))
        __sortingEnabled = self.list_songs.isSortingEnabled()
        self.list_songs.setSortingEnabled(False)
        item = self.list_songs.item(0)
        item.setText(_translate("PracticeScreen", "Laku noc moja mala barbiko"))
        item = self.list_songs.item(1)
        item.setText(_translate("PracticeScreen", "2"))
        item = self.list_songs.item(2)
        item.setText(_translate("PracticeScreen", "3"))
        item = self.list_songs.item(3)
        item.setText(_translate("PracticeScreen", "4"))
        item = self.list_songs.item(4)
        item.setText(_translate("PracticeScreen", "5"))
        item = self.list_songs.item(5)
        item.setText(_translate("PracticeScreen", "6"))
        item = self.list_songs.item(6)
        item.setText(_translate("PracticeScreen", "7"))
        item = self.list_songs.item(7)
        item.setText(_translate("PracticeScreen", "8"))
        item = self.list_songs.item(8)
        item.setText(_translate("PracticeScreen", "9"))
        item = self.list_songs.item(9)
        item.setText(_translate("PracticeScreen", "10"))
        item = self.list_songs.item(10)
        item.setText(_translate("PracticeScreen", "11"))
        item = self.list_songs.item(11)
        item.setText(_translate("PracticeScreen", "12"))
        item = self.list_songs.item(12)
        item.setText(_translate("PracticeScreen", "13"))
        item = self.list_songs.item(13)
        item.setText(_translate("PracticeScreen", "14"))
        item = self.list_songs.item(14)
        item.setText(_translate("PracticeScreen", "15"))
        item = self.list_songs.item(15)
        item.setText(_translate("PracticeScreen", "Laku noc moja mala barbiko"))
        item = self.list_songs.item(16)
        item.setText(_translate("PracticeScreen", "17"))
        item = self.list_songs.item(17)
        item.setText(_translate("PracticeScreen", "18"))
        item = self.list_songs.item(18)
        item.setText(_translate("PracticeScreen", "19"))
        item = self.list_songs.item(19)
        item.setText(_translate("PracticeScreen", "20"))
        self.list_songs.setSortingEnabled(__sortingEnabled)
        self.label_author.setText(_translate("PracticeScreen", "DINO MERLIN"))
        self.label_name.setText(_translate("PracticeScreen", "LAKU NOC MOJA MALA BARBIKO"))
        self.text_chords.setPlainText(_translate("PracticeScreen", "Gm\n"
"Sanjam sleces na moj prag\n"
"Gm\n"
"ja prostirem svilen sag\n"
"F\n"
"tvoja mokra stopala\n"
"Dm\n"
"sad bi tako plesala\n"
"\n"
"sanjam kisu crven krov\n"
"da se budim kao nov\n"
"sanjam davno sanjano\n"
"sto mi nije sudjeno.\n"
"\n"
"Prsti djeradan za tvoj vrat\n"
"mlade usne vode rat\n"
"i sve teze podnosim\n"
"sto te vrijeme odnosi.\n"
"\n"
"Ide ko zna koja zima\n"
"na put oko svijeta\n"
"lazu te kad kazu\n"
"da sam sretan.\n"
"\n"
"    Refren 2x\n"
"    A# F  A#       F\n"
"    La ku noc moja mala barbiko\n"
"          A#             F\n"
"    dzaba sve, al ja sam na te naviko\n"
"        D#     Cm\n"
"    usnama slucajno\n"
"        Gm    F     Gm\n"
"    ali srcem beskrajno"))
        self.label_time.setText(_translate("PracticeScreen", "12:34"))
        self.label_songs.setText(_translate("PracticeScreen", "0"))
import res_rc
