# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuScreen(object):
    def setupUi(self, MenuScreen):
        MenuScreen.setObjectName("MenuScreen")
        MenuScreen.resize(490, 650)
        MenuScreen.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MenuScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 490, 650))
        self.frame.setStyleSheet("QLabel {\n"
"    color: rgb(72,72,73);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_bg = QtWidgets.QLabel(self.frame)
        self.label_bg.setEnabled(True)
        self.label_bg.setGeometry(QtCore.QRect(0, 0, 490, 650))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_bg.setFont(font)
        self.label_bg.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_bg.setStyleSheet("border-image: url(:/images/images/bg.jpg);")
        self.label_bg.setText("")
        self.label_bg.setObjectName("label_bg")
        self.btn_exit = QtWidgets.QPushButton(self.frame)
        self.btn_exit.setGeometry(QtCore.QRect(30, 570, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton#btn_exit{\n"
"    border-image: url(:/menu/images/menu/exit.png);\n"
"}\n"
"QPushButton#btn_exit:hover {\n"
"    border-image: url(:/menu/images/menu/exit_hover.png);\n"
"}")
        self.btn_exit.setText("")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_practice = QtWidgets.QPushButton(self.frame)
        self.btn_practice.setEnabled(True)
        self.btn_practice.setGeometry(QtCore.QRect(30, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_practice.setFont(font)
        self.btn_practice.setStyleSheet("QPushButton#btn_practice {\n"
"    border-image: url(:/menu/images/menu/practice.png);\n"
"}\n"
"QPushButton#btn_practice:hover {\n"
"    border-image: url(:/menu/images/menu/practice_hover.png);\n"
"}")
        self.btn_practice.setText("")
        self.btn_practice.setObjectName("btn_practice")
        self.btn_songs = QtWidgets.QPushButton(self.frame)
        self.btn_songs.setGeometry(QtCore.QRect(30, 150, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_songs.setFont(font)
        self.btn_songs.setStyleSheet("QPushButton#btn_songs{\n"
"    border-image: url(:/menu/images/menu/songs.png);\n"
"}\n"
"QPushButton#btn_songs:hover {\n"
"    border-image: url(:/menu/images/menu/songs_hover.png);\n"
"}")
        self.btn_songs.setText("")
        self.btn_songs.setObjectName("btn_songs")
        self.btn_stats = QtWidgets.QPushButton(self.frame)
        self.btn_stats.setGeometry(QtCore.QRect(30, 210, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_stats.setFont(font)
        self.btn_stats.setStyleSheet("QPushButton#btn_stats{\n"
"    border-image: url(:/menu/images/menu/stats.png);\n"
"}\n"
"QPushButton#btn_stats:hover {\n"
"    border-image: url(:/menu/images/menu/stats_hover.png);\n"
"}")
        self.btn_stats.setText("")
        self.btn_stats.setObjectName("btn_stats")
        self.btn_sessions = QtWidgets.QPushButton(self.frame)
        self.btn_sessions.setGeometry(QtCore.QRect(30, 270, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sessions.setFont(font)
        self.btn_sessions.setStyleSheet("QPushButton#btn_sessions{\n"
"    border-image: url(:/menu/images/menu/sessions.png);\n"
"}\n"
"QPushButton#btn_sessions:hover {\n"
"    border-image: url(:/menu/images/menu/sessions_hover.png);\n"
"}")
        self.btn_sessions.setText("")
        self.btn_sessions.setObjectName("btn_sessions")
        self.btn_settings = QtWidgets.QPushButton(self.frame)
        self.btn_settings.setGeometry(QtCore.QRect(30, 390, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_settings.setFont(font)
        self.btn_settings.setStyleSheet("QPushButton#btn_settings{\n"
"    border-image: url(:/menu/images/menu/settings.png);\n"
"}\n"
"QPushButton#btn_settings:hover {\n"
"    border-image: url(:/menu/images/menu/settings_hover.png);\n"
"}")
        self.btn_settings.setText("")
        self.btn_settings.setObjectName("btn_settings")
        self.btn_about = QtWidgets.QPushButton(self.frame)
        self.btn_about.setGeometry(QtCore.QRect(30, 450, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_about.setFont(font)
        self.btn_about.setStyleSheet("QPushButton#btn_about{\n"
"    border-image: url(:/menu/images/menu/about.png);\n"
"}\n"
"QPushButton#btn_about:hover {\n"
"    border-image: url(:/menu/images/menu/about_hover.png);\n"
"}")
        self.btn_about.setText("")
        self.btn_about.setObjectName("btn_about")
        self.btn_top = QtWidgets.QPushButton(self.frame)
        self.btn_top.setGeometry(QtCore.QRect(30, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_top.setFont(font)
        self.btn_top.setStyleSheet("QPushButton#btn_top{\n"
"    border-image: url(:/menu/images/menu/top.png);\n"
"}\n"
"QPushButton#btn_top:hover {\n"
"    border-image: url(:/menu/images/menu/top_hover.png);\n"
"}")
        self.btn_top.setText("")
        self.btn_top.setObjectName("btn_top")
        self.btn_admin = QtWidgets.QPushButton(self.frame)
        self.btn_admin.setGeometry(QtCore.QRect(30, 510, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_admin.setFont(font)
        self.btn_admin.setStyleSheet("QPushButton#btn_admin{\n"
"    border-image: url(:/menu/images/menu/admin.png);\n"
"}\n"
"QPushButton#btn_admin:hover {\n"
"    border-image: url(:/menu/images/menu/admin_hover.png);\n"
"}")
        self.btn_admin.setText("")
        self.btn_admin.setObjectName("btn_admin")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 491, 51))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(72,72,73);\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.app_name = QtWidgets.QLabel(self.frame_2)
        self.app_name.setGeometry(QtCore.QRect(30, 13, 481, 50))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setStyleSheet("color: rgb(205,205,205);\n"
"background-color: rgba(0,0,0,0);")
        self.app_name.setObjectName("app_name")
        self.logo = QtWidgets.QLabel(self.frame_2)
        self.logo.setGeometry(QtCore.QRect(30, -24, 100, 100))
        self.logo.setStyleSheet("border-image: url(:/images/images/logo.jpg);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.logo.raise_()
        self.app_name.raise_()
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(-10, 130, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(-10, 190, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(-10, 250, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(-10, 310, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(-10, 370, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(-10, 430, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(-10, 490, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(-10, 550, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(-10, 610, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        MenuScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuScreen)
        QtCore.QMetaObject.connectSlotsByName(MenuScreen)

    def retranslateUi(self, MenuScreen):
        _translate = QtCore.QCoreApplication.translate
        MenuScreen.setWindowTitle(_translate("MenuScreen", "MainWindow"))
        self.app_name.setText(_translate("MenuScreen", "GUITAR AIO - Main Menu"))
        self.label_2.setText(_translate("MenuScreen", "Practice"))
        self.label_3.setText(_translate("MenuScreen", "Songs"))
        self.label_4.setText(_translate("MenuScreen", "Stats"))
        self.label_5.setText(_translate("MenuScreen", "Sessions"))
        self.label_6.setText(_translate("MenuScreen", "Top users"))
        self.label_7.setText(_translate("MenuScreen", "Settings"))
        self.label_8.setText(_translate("MenuScreen", "About"))
        self.label_9.setText(_translate("MenuScreen", "Admin"))
        self.label_10.setText(_translate("MenuScreen", "Exit"))
import res_rc
